### ISSUE TITLE
403 Forbidden when getting collaborators 

### ISSUE THREAD

**Issue by datastorm1337** [spring-projects/spring-social-github#35]
I am trying to use: repoOperations().getCollaborators
but I get following exception
Getting org.springframework.web.client.HttpClientErrorException: 403 Forbidden

It is a repo that is owned by logged in user.

It looks like getting repo's collaborators isn't a part of public github api. 
I do manage to get the collaborators list with postman when I authenticate. 

Which leads me to believe that this library isn't using the authentication to retrieve the data from github?

I may be wrong, but the fact is that I am getting that exception when I try to get a list of collaborators with this library.

**Comment by vkolodrevskiy** [comment]
You need to specify authorisation scope `user,repo`.
